version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    env_file: ../.env
    volumes:
      - ../backend:/app
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate || true &&
             python manage.py runserver 0.0.0.0:8000 || tail -f /dev/null"

  frontend:
    build: ../frontend
    environment:
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"

volumes:
  db_data:
  media:
